using System;
using System.Collections.Frozen;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace Sdl3Sharp.Ttf;

public static class ScriptExtensions
{
	private static readonly FrozenDictionary<Script, (string code, string name)> mData;
	private static readonly FrozenDictionary<string, Script> mCodeLookup;

	static ScriptExtensions()
	{
		// Please see the comment in the ModuleInitializer method for the reason why we're doing it this way instead of static field initializers.

		mData = FrozenDictionary.ToFrozenDictionary<Script, (string code, string name)>([
			new(unchecked((Script)166), ("Adlm", "Adlam")),
			new(unchecked((Script)439), ("Afak", "Afaka")),
			new(unchecked((Script)239), ("Aghb", "Caucasian Albanian")),
			new(unchecked((Script)338), ("Ahom", "Ahom, Tai Ahom")),
			new(unchecked((Script)160), ("Arab", "Arabic")),
			new(unchecked((Script)161), ("Aran", "Arabic (Nastaliq variant)")),
			new(unchecked((Script)124), ("Armi", "Imperial Aramaic")),
			new(unchecked((Script)230), ("Armn", "Armenian")),
			new(unchecked((Script)134), ("Avst", "Avestan")),
			new(unchecked((Script)360), ("Bali", "Balinese")),
			new(unchecked((Script)435), ("Bamu", "Bamum")),
			new(unchecked((Script)259), ("Bass", "Bassa Vah")),
			new(unchecked((Script)365), ("Batk", "Batak")),
			new(unchecked((Script)325), ("Beng", "Bengali (Bangla)")),
			new(unchecked((Script)258), ("Berf", "Beria Erfe")),
			new(unchecked((Script)334), ("Bhks", "Bhaiksuki")),
			new(unchecked((Script)550), ("Blis", "Blissymbols")),
			new(unchecked((Script)285), ("Bopo", "Bopomofo")),
			new(unchecked((Script)300), ("Brah", "Brahmi")),
			new(unchecked((Script)570), ("Brai", "Braille")),
			new(unchecked((Script)367), ("Bugi", "Buginese")),
			new(unchecked((Script)372), ("Buhd", "Buhid")),
			new(unchecked((Script)349), ("Cakm", "Chakma")),
			new(unchecked((Script)440), ("Cans", "Unified Canadian Aboriginal Syllabics")),
			new(unchecked((Script)201), ("Cari", "Carian")),
			new(unchecked((Script)358), ("Cham", "Cham")),
			new(unchecked((Script)445), ("Cher", "Cherokee")),
			new(unchecked((Script)298), ("Chis", "Chisoi")),
			new(unchecked((Script)109), ("Chrs", "Chorasmian")),
			new(unchecked((Script)291), ("Cirt", "Cirth")),
			new(unchecked((Script)204), ("Copt", "Coptic")),
			new(unchecked((Script)402), ("Cpmn", "Cypro-Minoan")),
			new(unchecked((Script)403), ("Cprt", "Cypriot syllabary")),
			new(unchecked((Script)220), ("Cyrl", "Cyrillic")),
			new(unchecked((Script)221), ("Cyrs", "Cyrillic (Old Church Slavonic variant)")),
			new(unchecked((Script)315), ("Deva", "Devanagari (Nagari)")),
			new(unchecked((Script)342), ("Diak", "Dives Akuru")),
			new(unchecked((Script)328), ("Dogr", "Dogra")),
			new(unchecked((Script)250), ("Dsrt", "Deseret (Mormon)")),
			new(unchecked((Script)755), ("Dupl", "Duployan shorthand, Duployan stenography")),
			new(unchecked((Script)70), ("Egyd", "Egyptian demotic")),
			new(unchecked((Script)60), ("Egyh", "Egyptian hieratic")),
			new(unchecked((Script)50), ("Egyp", "Egyptian hieroglyphs")),
			new(unchecked((Script)226), ("Elba", "Elbasan")),
			new(unchecked((Script)128), ("Elym", "Elymaic")),
			new(unchecked((Script)430), ("Ethi", "Ethiopic (Geʻez)")),
			new(unchecked((Script)164), ("Gara", "Garay")),
			new(unchecked((Script)241), ("Geok", "Khutsuri (Asomtavruli and Nuskhuri)")),
			new(unchecked((Script)240), ("Geor", "Georgian (Mkhedruli and Mtavruli)")),
			new(unchecked((Script)225), ("Glag", "Glagolitic")),
			new(unchecked((Script)312), ("Gong", "Gunjala Gondi")),
			new(unchecked((Script)313), ("Gonm", "Masaram Gondi")),
			new(unchecked((Script)206), ("Goth", "Gothic")),
			new(unchecked((Script)343), ("Gran", "Grantha")),
			new(unchecked((Script)200), ("Grek", "Greek")),
			new(unchecked((Script)320), ("Gujr", "Gujarati")),
			new(unchecked((Script)397), ("Gukh", "Gurung Khema")),
			new(unchecked((Script)310), ("Guru", "Gurmukhi")),
			new(unchecked((Script)503), ("Hanb", "Han with Bopomofo (alias for Han + Bopomofo)")),
			new(unchecked((Script)286), ("Hang", "Hangul (Hangŭl, Hangeul)")),
			new(unchecked((Script)500), ("Hani", "Han (Hanzi, Kanji, Hanja)")),
			new(unchecked((Script)371), ("Hano", "Hanunoo (Hanunóo)")),
			new(unchecked((Script)501), ("Hans", "Han (Simplified variant)")),
			new(unchecked((Script)502), ("Hant", "Han (Traditional variant)")),
			new(unchecked((Script)127), ("Hatr", "Hatran")),
			new(unchecked((Script)125), ("Hebr", "Hebrew")),
			new(unchecked((Script)410), ("Hira", "Hiragana")),
			new(unchecked((Script)80), ("Hluw", "Anatolian Hieroglyphs (Luwian Hieroglyphs, Hittite Hieroglyphs)")),
			new(unchecked((Script)450), ("Hmng", "Pahawh Hmong")),
			new(unchecked((Script)451), ("Hmnp", "Nyiakeng Puachue Hmong")),
			new(unchecked((Script)504), ("Hntl", "Han (Traditional variant) with Latin (alias for Hant + Latn)")),
			new(unchecked((Script)412), ("Hrkt", "Japanese syllabaries (alias for Hiragana + Katakana)")),
			new(unchecked((Script)176), ("Hung", "Old Hungarian (Hungarian Runic)")),
			new(unchecked((Script)610), ("Inds", "Indus (Harappan)")),
			new(unchecked((Script)210), ("Ital", "Old Italic (Etruscan, Oscan, etc.)")),
			new(unchecked((Script)284), ("Jamo", "Jamo (alias for Jamo subset of Hangul)")),
			new(unchecked((Script)361), ("Java", "Javanese")),
			new(unchecked((Script)413), ("Jpan", "Japanese (alias for Han + Hiragana + Katakana)")),
			new(unchecked((Script)510), ("Jurc", "Jurchen")),
			new(unchecked((Script)357), ("Kali", "Kayah Li")),
			new(unchecked((Script)411), ("Kana", "Katakana")),
			new(unchecked((Script)368), ("Kawi", "Kawi")),
			new(unchecked((Script)305), ("Khar", "Kharoshthi")),
			new(unchecked((Script)355), ("Khmr", "Khmer")),
			new(unchecked((Script)322), ("Khoj", "Khojki")),
			new(unchecked((Script)505), ("Kitl", "Khitan large script")),
			new(unchecked((Script)288), ("Kits", "Khitan small script")),
			new(unchecked((Script)345), ("Knda", "Kannada")),
			new(unchecked((Script)287), ("Kore", "Korean (alias for Hangul + Han)")),
			new(unchecked((Script)436), ("Kpel", "Kpelle")),
			new(unchecked((Script)396), ("Krai", "Kirat Rai")),
			new(unchecked((Script)317), ("Kthi", "Kaithi")),
			new(unchecked((Script)351), ("Lana", "Tai Tham (Lanna)")),
			new(unchecked((Script)356), ("Laoo", "Lao")),
			new(unchecked((Script)217), ("Latf", "Latin (Fraktur variant)")),
			new(unchecked((Script)216), ("Latg", "Latin (Gaelic variant)")),
			new(unchecked((Script)215), ("Latn", "Latin")),
			new(unchecked((Script)364), ("Leke", "Leke")),
			new(unchecked((Script)335), ("Lepc", "Lepcha (Róng)")),
			new(unchecked((Script)336), ("Limb", "Limbu")),
			new(unchecked((Script)400), ("Lina", "Linear A")),
			new(unchecked((Script)401), ("Linb", "Linear B")),
			new(unchecked((Script)399), ("Lisu", "Lisu (Fraser)")),
			new(unchecked((Script)437), ("Loma", "Loma")),
			new(unchecked((Script)202), ("Lyci", "Lycian")),
			new(unchecked((Script)116), ("Lydi", "Lydian")),
			new(unchecked((Script)314), ("Mahj", "Mahajani")),
			new(unchecked((Script)366), ("Maka", "Makasar")),
			new(unchecked((Script)140), ("Mand", "Mandaic, Mandaean")),
			new(unchecked((Script)139), ("Mani", "Manichaean")),
			new(unchecked((Script)332), ("Marc", "Marchen")),
			new(unchecked((Script)90), ("Maya", "Mayan hieroglyphs")),
			new(unchecked((Script)265), ("Medf", "Medefaidrin (Oberi Okaime, Oberi Ɔkaimɛ)")),
			new(unchecked((Script)438), ("Mend", "Mende Kikakui")),
			new(unchecked((Script)101), ("Merc", "Meroitic Cursive")),
			new(unchecked((Script)100), ("Mero", "Meroitic Hieroglyphs")),
			new(unchecked((Script)347), ("Mlym", "Malayalam")),
			new(unchecked((Script)324), ("Modi", "Modi, Moḍī")),
			new(unchecked((Script)145), ("Mong", "Mongolian")),
			new(unchecked((Script)218), ("Moon", "Moon (Moon code, Moon script, Moon type)")),
			new(unchecked((Script)264), ("Mroo", "Mro, Mru")),
			new(unchecked((Script)337), ("Mtei", "Meitei Mayek (Meithei, Meetei)")),
			new(unchecked((Script)323), ("Mult", "Multani")),
			new(unchecked((Script)350), ("Mymr", "Myanmar (Burmese)")),
			new(unchecked((Script)295), ("Nagm", "Nag Mundari")),
			new(unchecked((Script)311), ("Nand", "Nandinagari")),
			new(unchecked((Script)106), ("Narb", "Old North Arabian (Ancient North Arabian)")),
			new(unchecked((Script)159), ("Nbat", "Nabataean")),
			new(unchecked((Script)333), ("Newa", "Newa, Newar, Newari, Nepāla lipi")),
			new(unchecked((Script)85), ("Nkdb", "Naxi Dongba (na²¹ɕi³³ to³³ba²¹, Nakhi Tomba)")),
			new(unchecked((Script)420), ("Nkgb", "Naxi Geba (na²¹ɕi³³ gʌ²¹ba²¹, 'Na-'Khi ²Ggŏ-¹baw, Nakhi Geba)")),
			new(unchecked((Script)165), ("Nkoo", "N’Ko")),
			new(unchecked((Script)499), ("Nshu", "Nüshu")),
			new(unchecked((Script)212), ("Ogam", "Ogham")),
			new(unchecked((Script)261), ("Olck", "Ol Chiki (Ol Cemet’, Ol, Santali)")),
			new(unchecked((Script)296), ("Onao", "Ol Onal")),
			new(unchecked((Script)175), ("Orkh", "Old Turkic, Orkhon Runic")),
			new(unchecked((Script)327), ("Orya", "Oriya (Odia)")),
			new(unchecked((Script)219), ("Osge", "Osage")),
			new(unchecked((Script)260), ("Osma", "Osmanya")),
			new(unchecked((Script)143), ("Ougr", "Old Uyghur")),
			new(unchecked((Script)126), ("Palm", "Palmyrene")),
			new(unchecked((Script)263), ("Pauc", "Pau Cin Hau")),
			new(unchecked((Script)15), ("Pcun", "Proto-Cuneiform")),
			new(unchecked((Script)16), ("Pelm", "Proto-Elamite")),
			new(unchecked((Script)227), ("Perm", "Old Permic")),
			new(unchecked((Script)331), ("Phag", "Phags-pa")),
			new(unchecked((Script)131), ("Phli", "Inscriptional Pahlavi")),
			new(unchecked((Script)132), ("Phlp", "Psalter Pahlavi")),
			new(unchecked((Script)133), ("Phlv", "Book Pahlavi")),
			new(unchecked((Script)115), ("Phnx", "Phoenician")),
			new(unchecked((Script)293), ("Piqd", "Klingon (KLI pIqaD)")),
			new(unchecked((Script)282), ("Plrd", "Miao (Pollard)")),
			new(unchecked((Script)130), ("Prti", "Inscriptional Parthian")),
			new(unchecked((Script)103), ("Psin", "Proto-Sinaitic")),
			new(unchecked((Script)900), ("Qaaa", "Reserved for private use (start)")),
			new(unchecked((Script)949), ("Qabx", "Reserved for private use (end)")),
			new(unchecked((Script)303), ("Ranj", "Ranjana")),
			new(unchecked((Script)363), ("Rjng", "Rejang (Redjang, Kaganga)")),
			new(unchecked((Script)167), ("Rohg", "Hanifi Rohingya")),
			new(unchecked((Script)620), ("Roro", "Rongorongo")),
			new(unchecked((Script)211), ("Runr", "Runic")),
			new(unchecked((Script)123), ("Samr", "Samaritan")),
			new(unchecked((Script)292), ("Sara", "Sarati")),
			new(unchecked((Script)105), ("Sarb", "Old South Arabian")),
			new(unchecked((Script)344), ("Saur", "Saurashtra")),
			new(unchecked((Script)590), ("Seal", "(Small) Seal")),
			new(unchecked((Script)95), ("Sgnw", "SignWriting")),
			new(unchecked((Script)281), ("Shaw", "Shavian (Shaw)")),
			new(unchecked((Script)319), ("Shrd", "Sharada, Śāradā")),
			new(unchecked((Script)530), ("Shui", "Shuishu")),
			new(unchecked((Script)302), ("Sidd", "Siddham, Siddhaṃ, Siddhamātṛkā")),
			new(unchecked((Script)180), ("Sidt", "Sidetic")),
			new(unchecked((Script)318), ("Sind", "Khudawadi, Sindhi")),
			new(unchecked((Script)348), ("Sinh", "Sinhala")),
			new(unchecked((Script)141), ("Sogd", "Sogdian")),
			new(unchecked((Script)142), ("Sogo", "Old Sogdian")),
			new(unchecked((Script)398), ("Sora", "Sora Sompeng")),
			new(unchecked((Script)329), ("Soyo", "Soyombo")),
			new(unchecked((Script)362), ("Sund", "Sundanese")),
			new(unchecked((Script)274), ("Sunu", "Sunuwar")),
			new(unchecked((Script)316), ("Sylo", "Syloti Nagri")),
			new(unchecked((Script)135), ("Syrc", "Syriac")),
			new(unchecked((Script)138), ("Syre", "Syriac (Estrangelo variant)")),
			new(unchecked((Script)137), ("Syrj", "Syriac (Western variant)")),
			new(unchecked((Script)136), ("Syrn", "Syriac (Eastern variant)")),
			new(unchecked((Script)373), ("Tagb", "Tagbanwa")),
			new(unchecked((Script)321), ("Takr", "Takri, Ṭākrī, Ṭāṅkrī")),
			new(unchecked((Script)353), ("Tale", "Tai Le")),
			new(unchecked((Script)354), ("Talu", "New Tai Lue")),
			new(unchecked((Script)346), ("Taml", "Tamil")),
			new(unchecked((Script)520), ("Tang", "Tangut")),
			new(unchecked((Script)359), ("Tavt", "Tai Viet")),
			new(unchecked((Script)380), ("Tayo", "Tai Yo")),
			new(unchecked((Script)340), ("Telu", "Telugu")),
			new(unchecked((Script)290), ("Teng", "Tengwar")),
			new(unchecked((Script)120), ("Tfng", "Tifinagh (Berber)")),
			new(unchecked((Script)370), ("Tglg", "Tagalog (Baybayin, Alibata)")),
			new(unchecked((Script)170), ("Thaa", "Thaana")),
			new(unchecked((Script)352), ("Thai", "Thai")),
			new(unchecked((Script)330), ("Tibt", "Tibetan")),
			new(unchecked((Script)326), ("Tirh", "Tirhuta")),
			new(unchecked((Script)275), ("Tnsa", "Tangsa")),
			new(unchecked((Script)229), ("Todr", "Todhri")),
			new(unchecked((Script)299), ("Tols", "Tolong Siki")),
			new(unchecked((Script)294), ("Toto", "Toto")),
			new(unchecked((Script)341), ("Tutg", "Tulu-Tigalari")),
			new(unchecked((Script)40), ("Ugar", "Ugaritic")),
			new(unchecked((Script)470), ("Vaii", "Vai")),
			new(unchecked((Script)280), ("Visp", "Visible Speech")),
			new(unchecked((Script)228), ("Vith", "Vithkuqi")),
			new(unchecked((Script)262), ("Wara", "Warang Citi (Varang Kshiti)")),
			new(unchecked((Script)283), ("Wcho", "Wancho")),
			new(unchecked((Script)480), ("Wole", "Woleai")),
			new(unchecked((Script)30), ("Xpeo", "Old Persian")),
			new(unchecked((Script)20), ("Xsux", "Cuneiform, Sumero-Akkadian")),
			new(unchecked((Script)192), ("Yezi", "Yezidi")),
			new(unchecked((Script)460), ("Yiii", "Yi")),
			new(unchecked((Script)339), ("Zanb", "Zanabazar Square (Zanabazarin Dörböljin Useg, Xewtee Dörböljin Bicig, Horizontal Square Script)")),
			new(unchecked((Script)994), ("Zinh", "Code for inherited script")),
			new(unchecked((Script)995), ("Zmth", "Mathematical notation")),
			new(unchecked((Script)993), ("Zsye", "Symbols (Emoji variant)")),
			new(unchecked((Script)996), ("Zsym", "Symbols")),
			new(unchecked((Script)997), ("Zxxx", "Code for unwritten documents")),
			new(unchecked((Script)998), ("Zyyy", "Code for undetermined script")),
			new(unchecked((Script)999), ("Zzzz", "Code for uncoded script")),
		]);

		mCodeLookup = FrozenDictionary.ToFrozenDictionary<string, Script>([
			new("adlm", unchecked((Script)166)),
			new("afak", unchecked((Script)439)),
			new("aghb", unchecked((Script)239)),
			new("ahom", unchecked((Script)338)),
			new("arab", unchecked((Script)160)),
			new("aran", unchecked((Script)161)),
			new("armi", unchecked((Script)124)),
			new("armn", unchecked((Script)230)),
			new("avst", unchecked((Script)134)),
			new("bali", unchecked((Script)360)),
			new("bamu", unchecked((Script)435)),
			new("bass", unchecked((Script)259)),
			new("batk", unchecked((Script)365)),
			new("beng", unchecked((Script)325)),
			new("berf", unchecked((Script)258)),
			new("bhks", unchecked((Script)334)),
			new("blis", unchecked((Script)550)),
			new("bopo", unchecked((Script)285)),
			new("brah", unchecked((Script)300)),
			new("brai", unchecked((Script)570)),
			new("bugi", unchecked((Script)367)),
			new("buhd", unchecked((Script)372)),
			new("cakm", unchecked((Script)349)),
			new("cans", unchecked((Script)440)),
			new("cari", unchecked((Script)201)),
			new("cham", unchecked((Script)358)),
			new("cher", unchecked((Script)445)),
			new("chis", unchecked((Script)298)),
			new("chrs", unchecked((Script)109)),
			new("cirt", unchecked((Script)291)),
			new("copt", unchecked((Script)204)),
			new("cpmn", unchecked((Script)402)),
			new("cprt", unchecked((Script)403)),
			new("cyrl", unchecked((Script)220)),
			new("cyrs", unchecked((Script)221)),
			new("deva", unchecked((Script)315)),
			new("diak", unchecked((Script)342)),
			new("dogr", unchecked((Script)328)),
			new("dsrt", unchecked((Script)250)),
			new("dupl", unchecked((Script)755)),
			new("egyd", unchecked((Script)70)),
			new("egyh", unchecked((Script)60)),
			new("egyp", unchecked((Script)50)),
			new("elba", unchecked((Script)226)),
			new("elym", unchecked((Script)128)),
			new("ethi", unchecked((Script)430)),
			new("gara", unchecked((Script)164)),
			new("geok", unchecked((Script)241)),
			new("geor", unchecked((Script)240)),
			new("glag", unchecked((Script)225)),
			new("gong", unchecked((Script)312)),
			new("gonm", unchecked((Script)313)),
			new("goth", unchecked((Script)206)),
			new("gran", unchecked((Script)343)),
			new("grek", unchecked((Script)200)),
			new("gujr", unchecked((Script)320)),
			new("gukh", unchecked((Script)397)),
			new("guru", unchecked((Script)310)),
			new("hanb", unchecked((Script)503)),
			new("hang", unchecked((Script)286)),
			new("hani", unchecked((Script)500)),
			new("hano", unchecked((Script)371)),
			new("hans", unchecked((Script)501)),
			new("hant", unchecked((Script)502)),
			new("hatr", unchecked((Script)127)),
			new("hebr", unchecked((Script)125)),
			new("hira", unchecked((Script)410)),
			new("hluw", unchecked((Script)80)),
			new("hmng", unchecked((Script)450)),
			new("hmnp", unchecked((Script)451)),
			new("hntl", unchecked((Script)504)),
			new("hrkt", unchecked((Script)412)),
			new("hung", unchecked((Script)176)),
			new("inds", unchecked((Script)610)),
			new("ital", unchecked((Script)210)),
			new("jamo", unchecked((Script)284)),
			new("java", unchecked((Script)361)),
			new("jpan", unchecked((Script)413)),
			new("jurc", unchecked((Script)510)),
			new("kali", unchecked((Script)357)),
			new("kana", unchecked((Script)411)),
			new("kawi", unchecked((Script)368)),
			new("khar", unchecked((Script)305)),
			new("khmr", unchecked((Script)355)),
			new("khoj", unchecked((Script)322)),
			new("kitl", unchecked((Script)505)),
			new("kits", unchecked((Script)288)),
			new("knda", unchecked((Script)345)),
			new("kore", unchecked((Script)287)),
			new("kpel", unchecked((Script)436)),
			new("krai", unchecked((Script)396)),
			new("kthi", unchecked((Script)317)),
			new("lana", unchecked((Script)351)),
			new("laoo", unchecked((Script)356)),
			new("latf", unchecked((Script)217)),
			new("latg", unchecked((Script)216)),
			new("latn", unchecked((Script)215)),
			new("leke", unchecked((Script)364)),
			new("lepc", unchecked((Script)335)),
			new("limb", unchecked((Script)336)),
			new("lina", unchecked((Script)400)),
			new("linb", unchecked((Script)401)),
			new("lisu", unchecked((Script)399)),
			new("loma", unchecked((Script)437)),
			new("lyci", unchecked((Script)202)),
			new("lydi", unchecked((Script)116)),
			new("mahj", unchecked((Script)314)),
			new("maka", unchecked((Script)366)),
			new("mand", unchecked((Script)140)),
			new("mani", unchecked((Script)139)),
			new("marc", unchecked((Script)332)),
			new("maya", unchecked((Script)90)),
			new("medf", unchecked((Script)265)),
			new("mend", unchecked((Script)438)),
			new("merc", unchecked((Script)101)),
			new("mero", unchecked((Script)100)),
			new("mlym", unchecked((Script)347)),
			new("modi", unchecked((Script)324)),
			new("mong", unchecked((Script)145)),
			new("moon", unchecked((Script)218)),
			new("mroo", unchecked((Script)264)),
			new("mtei", unchecked((Script)337)),
			new("mult", unchecked((Script)323)),
			new("mymr", unchecked((Script)350)),
			new("nagm", unchecked((Script)295)),
			new("nand", unchecked((Script)311)),
			new("narb", unchecked((Script)106)),
			new("nbat", unchecked((Script)159)),
			new("newa", unchecked((Script)333)),
			new("nkdb", unchecked((Script)85)),
			new("nkgb", unchecked((Script)420)),
			new("nkoo", unchecked((Script)165)),
			new("nshu", unchecked((Script)499)),
			new("ogam", unchecked((Script)212)),
			new("olck", unchecked((Script)261)),
			new("onao", unchecked((Script)296)),
			new("orkh", unchecked((Script)175)),
			new("orya", unchecked((Script)327)),
			new("osge", unchecked((Script)219)),
			new("osma", unchecked((Script)260)),
			new("ougr", unchecked((Script)143)),
			new("palm", unchecked((Script)126)),
			new("pauc", unchecked((Script)263)),
			new("pcun", unchecked((Script)15)),
			new("pelm", unchecked((Script)16)),
			new("perm", unchecked((Script)227)),
			new("phag", unchecked((Script)331)),
			new("phli", unchecked((Script)131)),
			new("phlp", unchecked((Script)132)),
			new("phlv", unchecked((Script)133)),
			new("phnx", unchecked((Script)115)),
			new("piqd", unchecked((Script)293)),
			new("plrd", unchecked((Script)282)),
			new("prti", unchecked((Script)130)),
			new("psin", unchecked((Script)103)),
			new("qaaa", unchecked((Script)900)),
			new("qabx", unchecked((Script)949)),
			new("ranj", unchecked((Script)303)),
			new("rjng", unchecked((Script)363)),
			new("rohg", unchecked((Script)167)),
			new("roro", unchecked((Script)620)),
			new("runr", unchecked((Script)211)),
			new("samr", unchecked((Script)123)),
			new("sara", unchecked((Script)292)),
			new("sarb", unchecked((Script)105)),
			new("saur", unchecked((Script)344)),
			new("seal", unchecked((Script)590)),
			new("sgnw", unchecked((Script)95)),
			new("shaw", unchecked((Script)281)),
			new("shrd", unchecked((Script)319)),
			new("shui", unchecked((Script)530)),
			new("sidd", unchecked((Script)302)),
			new("sidt", unchecked((Script)180)),
			new("sind", unchecked((Script)318)),
			new("sinh", unchecked((Script)348)),
			new("sogd", unchecked((Script)141)),
			new("sogo", unchecked((Script)142)),
			new("sora", unchecked((Script)398)),
			new("soyo", unchecked((Script)329)),
			new("sund", unchecked((Script)362)),
			new("sunu", unchecked((Script)274)),
			new("sylo", unchecked((Script)316)),
			new("syrc", unchecked((Script)135)),
			new("syre", unchecked((Script)138)),
			new("syrj", unchecked((Script)137)),
			new("syrn", unchecked((Script)136)),
			new("tagb", unchecked((Script)373)),
			new("takr", unchecked((Script)321)),
			new("tale", unchecked((Script)353)),
			new("talu", unchecked((Script)354)),
			new("taml", unchecked((Script)346)),
			new("tang", unchecked((Script)520)),
			new("tavt", unchecked((Script)359)),
			new("tayo", unchecked((Script)380)),
			new("telu", unchecked((Script)340)),
			new("teng", unchecked((Script)290)),
			new("tfng", unchecked((Script)120)),
			new("tglg", unchecked((Script)370)),
			new("thaa", unchecked((Script)170)),
			new("thai", unchecked((Script)352)),
			new("tibt", unchecked((Script)330)),
			new("tirh", unchecked((Script)326)),
			new("tnsa", unchecked((Script)275)),
			new("todr", unchecked((Script)229)),
			new("tols", unchecked((Script)299)),
			new("toto", unchecked((Script)294)),
			new("tutg", unchecked((Script)341)),
			new("ugar", unchecked((Script)40)),
			new("vaii", unchecked((Script)470)),
			new("visp", unchecked((Script)280)),
			new("vith", unchecked((Script)228)),
			new("wara", unchecked((Script)262)),
			new("wcho", unchecked((Script)283)),
			new("wole", unchecked((Script)480)),
			new("xpeo", unchecked((Script)30)),
			new("xsux", unchecked((Script)20)),
			new("yezi", unchecked((Script)192)),
			new("yiii", unchecked((Script)460)),
			new("zanb", unchecked((Script)339)),
			new("zinh", unchecked((Script)994)),
			new("zmth", unchecked((Script)995)),
			new("zsye", unchecked((Script)993)),
			new("zsym", unchecked((Script)996)),
			new("zxxx", unchecked((Script)997)),
			new("zyyy", unchecked((Script)998)),
			new("zzzz", unchecked((Script)999)),
		], StringComparer.OrdinalIgnoreCase);
	}

#pragma warning disable CA2255 // I'm sorry, but we're doing this now...
	[ModuleInitializer]
#pragma warning restore CA2255
	internal static void ModuleInitializer()
	{
		// This forces the frozen dictionaries to be initialized at module load time (via the static type constructor).
		// Otherwise, if we would just rely on static initialization, the first access to an extension property or method would trigger the frozen dictionaries to get initialized.
		//
		// Initializing a frozen dictionary is a very expensive operation, but comes with the benefit of accessing an initialized frozen dictionary being very fast!
		//
		// That's why we want to move initialization time into module load time, so we don't risk the first access to, for example, ScriptExtensions.Code to be very slow.
		// With that, accessing ScriptExtensions.Code, ScriptExtensions.Name, or ScriptExtensions.TryFromCode, etc., will be fast at all times, even the first time,
		// thanks to the frozen dictionaries being already initialized and frozen dictionaries being very optimized for fast access.

		RuntimeHelpers.RunClassConstructor(typeof(ScriptExtensions).TypeHandle);
	}

	[DoesNotReturn]
	private static void FailUnrecognizedScript(Script script) => throw new InvalidOperationException($"Unrecognized script: {script}");

	extension(Script)
	{
		public static bool TryFromCode(string code, out Script script)
			=> mCodeLookup.TryGetValue(code.ToLowerInvariant(), out script);
	}

	extension(Script script)
	{
		public string Code
		{
			get
			{
				if (!mData.TryGetValue(script, out var data))
				{
					FailUnrecognizedScript(script);
				}

				return data.code;
			}
		}

		public string Name
		{
			get
			{
				if (!mData.TryGetValue(script, out var data))
				{
					FailUnrecognizedScript(script);
				}

				return data.name;
			}
		}
	}
}
